# Generated by Django 3.2 on 2021-05-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210504_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(blank=True, max_length=300, verbose_name='описание'),
        ),
    ]
