# Generated by Django 3.2 on 2021-05-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='src',
        ),
    ]
